//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congregation
    {
        public Congregation()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Meetings = new HashSet<Meeting>();
            this.MeetingAssignments = new HashSet<MeetingAssignment>();
            this.Members = new HashSet<Member>();
            this.MemberAssignments = new HashSet<MemberAssignment>();
            this.ScheduleDates = new HashSet<ScheduleDate>();
        }
    
        public int Id { get; set; }
        public string CongregationName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string WeekMeetingDay { get; set; }
        public string WeekMeetingTime { get; set; }
        public string PublicMeetingDay { get; set; }
        public string PublicMeetingTime { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<MeetingAssignment> MeetingAssignments { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<MemberAssignment> MemberAssignments { get; set; }
        public virtual ICollection<ScheduleDate> ScheduleDates { get; set; }
    }
}
