//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingManagerEntities : DbContext
    {
        public MeetingManagerEntities()
            : base("name=MeetingManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assignment> Assignments { get; set; }
        public DbSet<Congregation> Congregations { get; set; }
        public DbSet<Meeting> Meetings { get; set; }
        public DbSet<MeetingAssignment> MeetingAssignments { get; set; }
        public DbSet<MeetingDescription> MeetingDescriptions { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberAssignment> MemberAssignments { get; set; }
        public DbSet<ScheduleDate> ScheduleDates { get; set; }
        public DbSet<ServiceGroup> ServiceGroups { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UnavailableDate> UnavailableDates { get; set; }
    }
}
